### ISSUE TITLE
Import of carbon c relay dashboard has broken wallTime graphs

### ISSUE THREAD

**Issue by trenb** [matejzero/grafana-dashboards#4]
Thanks for this dashboard. I found an issue with how the wallTime graphs have set the units to "Âµs" instead of "µs". I have proposed [PR#3](https://github.com/matejzero/grafana-dashboards/pull/3) to resolve this.

**Comment by trenb** [comment]
Looks like this has already been merged. Thanks! Closing.

**Comment by matejzero** [comment]
Thanks for noticing and PR.

I need to revisit the template when I have some time and check if there are any new metrics.

New revision uploaded to Grafana.org.
